---
- name: Create user group
  group:
    name: '{{ user_group }}'
    system: yes
    state: present

- name: Create exporter user
  user:
    name: '{{ user_login }}'
    group: '{{ user_group }}'
    system: yes
    create_home: no

- name: Download node exporter archive
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.9.1/node_exporter-1.9.1.linux-arm64.tar.gz"
    dest: "/tmp/node_exporter.tar.gz"
    force: yes

- name: Extract node exporter archive
  unarchive:
    src: "/tmp/node_exporter.tar.gz"
    dest: /opt/
    remote_src: yes
    owner: '{{ user_login }}'
    group: '{{ user_group }}'
    mode: '0755'

- name: Move node exporter binary files
  copy:
    src: "/opt/node_exporter-1.9.1.linux-arm64/node_exporter"
    dest: /usr/local/bin/
    remote_src: yes
    owner: '{{ user_login }}'
    group: '{{ user_group }}'
    mode: '0755'

- name: Create node exporter systemd service file
  template:
    src: node_exporter.service.j2
    dest: "{{ node_exporter_service_file }}"
    owner: root
    group: root
    mode: '0644'

- name: Start node exporter service
  systemd:
    name: node_exporter
    state: started
    enabled: yes
    daemon_reload: yes
  register: status
