- name: Setup master DB
  hosts: beta
  vars:
    db_id: 1
  roles:
    - mysql-master
    - mysql-init-db
  tags:
    - master
    - db

- name: Setup WordPress
  hosts: alpha
  vars:
    db_host: "{{ hostvars['beta']['internal_host'] }}"
  roles:
    - apache
    - wordpress
  tags:
    - web
    - wordpress
