- name: Setup master DB
  hosts: beta
  vars:
    db_id: 1
  roles:
    - mysql-master
  tags:
    - master
    - db

- name: Setup slave DB
  hosts: gamma
  vars:
    db_id: 2
    master_host: "{{ hostvars['beta']['internal_host'] }}"
  roles:
    - mysql-slave
  tags:
    - slave
    - db

- name: Create database and user for WordPress
  hosts: beta
  roles:
    - mysql-init-db
  tags:
    - db

- name: Setup WordPress
  hosts: alpha
  vars:
    db_host: "{{ hostvars['beta']['internal_host'] }}"
  roles:
    - apache
    - wordpress
  tags:
    - web
    - wordpress

- name: Install node exporters
  hosts: all
  roles:
    - node-exporter
  tags:
    - monitoring

- name: Setup Monitoring system
  hosts: delta
  roles:
    - prometheus
    - grafana
  tags:
    - prometheus
    - grafana
    - monitoring
