---
- name: Create user group
  group:
    name: '{{ user_group }}'
    system: yes
    state: present

- name: Create wordpress user
  user:
    name: '{{ user_login }}'
    group: '{{ user_group }}'
    system: yes
    create_home: no

- name: Install Dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ dependencies }}"

- name: Download WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/
    remote_src: yes
    owner: '{{ user_login }}'
    group: '{{ user_group }}'
    mode: '0755'

- name: Move WordPress files
  copy:
    src: /var/www/wordpress/
    dest: /var/www/html/
    remote_src: yes
    owner: '{{ user_login }}'
    group: '{{ user_group }}'
    mode: '0755'

- name: Generate wp-config.php from template
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wp-config.php
    owner: '{{ user_login }}'
    group: '{{ user_group }}'
    mode: '0644'
  notify: Restart Apache
