---
- name: Create MySQL user
  mysql_user:
    login_user: "{{ db_root_user }}"
    login_host: "{{ db_host }}"
    login_port: "{{ db_port }}"
    login_unix_socket: "{{ db_login_unix_socket}}"
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    state: present
    host: "%"
    priv: "*.*:ALL"

- name: Create database
  mysql_db:
    name: "{{ db_name }}"
    state: present
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    login_host: "{{ db_host }}"
    login_port: "{{ db_port }}"
